spring.application.name=agent-service

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.org.springframework.ai=DEBUG
logging.level.com.davidozzo=DEBUG

spring.mongodb.uri=mongodb://admin:secret@192.168.1.20:27017/orderintelligence?authSource=admin

spring.ai.ollama.base-url=http://192.168.1.20:11434
spring.ai.ollama.chat.options.model=ibm/granite4:1b